### ISSUE TITLE
Remove job funcitonality unusable

### ISSUE THREAD

**Issue by MrDarthShoe** [mvniekerk/tokio-cron-scheduler#1]
Removing job from `JobScheduler` seems to be unusable.
`remove` function takes `Uuid` of job which user want to remove:
```rust
pub fn remove(&mut self, to_be_removed: &Uuid) -> Result<(), Box<dyn std::error::Error + '_>>
```
However, it seems that user cannot get Uuid of created job, because it is marked as private outside crate:
```rust
pub struct JobLocked(pub(crate) Arc<RwLock<Job>>);
```

Possible solutions:
- remove `pub(crate)` from `JobLocked` definition
- add `get_uuid` function

**Comment by mvniekerk** [comment]
Thank you for this report.

I've added the functionality on v0.1.3 and added it to the example, have a look and tell me if it works for you.

**Comment by mvniekerk** [comment]
BTW, the UUID is added as a parameter into the run closure (1st param) if you want to get the UUID on the run callback.

**Comment by MrDarthShoe** [comment]
Removing jobs on the fly works now.
Thanks!
