### ISSUE TITLE
Should have a way to deal with graceful shutdown

### ISSUE THREAD

**Issue by dialtone** [mvniekerk/tokio-cron-scheduler#2]
This crate should use `tokio::signal::ctrl_c()` to deal with graceful shutdown, for example you could change the `JobScheduler::start()` function like this:

```rust
async fn run_scheduler(sched: &JobScheduler) {
    let jl = sched.clone();

    let interrupt = tokio::signal::ctrl_c().fuse();
    let jh = tokio::spawn(async move {
        loop {
            tokio::time::sleep(core::time::Duration::from_millis(500)).await;
            let mut jsl = jl.clone();
            let tick = jsl.tick();
            if let Err(e) = tick {
                eprintln!("Error on job scheduler tick {:?}", e);
                break;
            }
        }
    })
    .fuse();

    pin_mut!(interrupt, jh);
    select!(
        _r = jh => {},
        res = interrupt => {
            if let Err(e) = res {
                tracing::error!("couldn't bind to ctrl+c {:?}", e);
            }
        }
    );
}
```

**Comment by mvniekerk** [comment]
Hi @dialtone 
Thank you for the report. Will be investigating and thinking of something how to do it.

**Comment by sp1ff** [comment]
I'd be interested in a general mechanism for graceful shutdown (not just Ctrl-C). [hyper](https://github.com/hyperium/hyper) offers a [mechanism](https://docs.rs/hyper/0.14.16/hyper/server/struct.Server.html#method.with_graceful_shutdown) where you can give a service a future whose resolution signals the server to shutdown.

**Comment by mvniekerk** [comment]
Hi @dialtone and @sp1ff . Please check out v0.5 - this should have it now. Note also the `signal` feature flag that will allow the system to be notified on a ctrl+c event.

**Comment by sp1ff** [comment]
@mvniekerk I'm confused. If I call `let h = start().unwrap();` I get a `JoinHandle` to a spawned task. Cool. When I call `shutdown()` I see the tasks are removed, but the future never completes. If I call `join!(h)` it just blocks forever. Is that intentional?
