### ISSUE TITLE
Missing `impl Error for JobSchedulerError`

### ISSUE THREAD

**Issue by Czocher** [mvniekerk/tokio-cron-scheduler#23]
Adding and `std::error::Error` implmenentation for `JobSchedulerErrror` would make it much simpler to use with some error handling libraries, such as `eyre`.

I suggest using [thiserror](https://github.com/dtolnay/thiserror) to auto-generate an implementation.

@mvniekerk if you find this to be a good idea I can implement it, just notify me ;).

**Comment by mvniekerk** [comment]
Hi @Czocher 
Check out v0.7.0, it implements std::error::Error now.
