### ISSUE TITLE
Can 'tokio-cron-scheduler' support run in LOCAL time?

### ISSUE THREAD

**Issue by rts-gordon** [mvniekerk/tokio-cron-scheduler#24]
Hi @mvniekerk 
  I known that 'tokio-cron-scheduler' run in UTC, but under some scenario we need run cronjob in LOCAL time, so would you like to implement this feature?   Thank you very much.

**Comment by palstek** [comment]
+1
I have a project where the job scheduling needs to be done in LOCAL time too. It needs to work across change from daylight savings time to normal time and vice versa. I like to implement this project in Rust.
Any hints where to look in the source code to add this feature myself are welcome?

**Comment by dumbasPL** [comment]
any progress on this? Linux cron uses local system time, so most users will expect cron jobs they configure to run at system time, not UTC.

**Comment by Hexagon** [comment]
@mvniekerk If you migrate from cron to croner , there is time zone support - and support for extended syntax. Basically croner uses whatever timezone is supplied through a DateTime<Tz>, so you can pass Utc::now, Local::now or a datetime with and timezone

See the "Why croner" section for a comparison

https://github.com/hexagon/croner-rust

**Comment by mvniekerk** [comment]
Hi all (@Hexagon , @rts-gordon , @dumbasPL )
Did you check the latest release of this?
