### ISSUE TITLE
There is no way to define and use customized job store

### ISSUE THREAD

**Issue by gy0801151351** [mvniekerk/tokio-cron-scheduler#26]
The trait "MetaDataStorage", "NotificationStore" are not public to outer crates, and I cannot define my customized store.

**Comment by mvniekerk** [comment]
Hi @gy0801151351 
Kindly update to 0.7.4. It should be made public now.

**Comment by gy0801151351** [comment]
I'am sorry about that, the super traits of "MetaDataStorage", "NotificationStore" are not public in version 0.7.4. Because I want to use your crate in my project, but I use neither postgresql nor nats to persist job store.
