### ISSUE TITLE
Example is out of date

### ISSUE THREAD

**Issue by inferiorhumanorgans** [mvniekerk/tokio-cron-scheduler#29]
e.g.

```rust
let mut sched = JobScheduler::new();

sched.add(Job::new("1/10 * * * * *", |uuid, l| {
    println!("I run every 10 seconds");
}).unwrap());
```

`JobScheduler::new` returns a `Result` so that won't work.

```rust
sched.start().await;
```

`start` returns a `Result` over `()` and not a future so `await` won't/can't work.

**Comment by mvniekerk** [comment]
Thank you @inferiorhumanorgans for the bug report. I've updated the README accordingly and the docs.

**Comment by inferiorhumanorgans** [comment]
Any thoughts on having start return the `JoinHandle` instead of `()` so we can call await on the result?
