### ISSUE TITLE
Lots of problems in documentation

### ISSUE THREAD

**Issue by krojew** [mvniekerk/tokio-cron-scheduler#3]
While the crate works as expected, there are a lot of problems with the documentation. It looks like much of the descriptions were copy-pasted (e.g. a repeated job is described as one shot). Doc examples have not been tested and a lot of them is invalid at this point.

**Comment by mvniekerk** [comment]
Hi Krojew
I'll have to check up on this. Thank you for reporting

**Comment by mvniekerk** [comment]
Hi @krojew  - updated.
