### ISSUE TITLE
Can there has an api to get a job next_run_time?

### ISSUE THREAD

**Issue by Hellager** [mvniekerk/tokio-cron-scheduler#32]
Thanks for your greet job, this crate works very well.
I did found that there's a function [time_till_next_job](https://docs.rs/tokio-cron-scheduler/latest/tokio_cron_scheduler/struct.JobScheduler.html#method.time_till_next_job) but it's not specified for a job,
can there has an api to get a specific job's next_run_time like this [get_next_run_time](https://apscheduler.readthedocs.io/en/3.x/modules/jobstores/base.html?highlight=next#apscheduler.jobstores.base.BaseJobStore.get_next_run_time)?

**Comment by Hellager** [comment]
For now, it's ok to do it like this
```rust
// after the JobScheduler start
use cron::{Schedule as Cron_Schedule};
use chrono::{Utc, DateTime};
use std::str::FromStr;

.....
let cron_expression = "1/10 * * * * *";
sched.add(Job::new("1/10 * * * * *", |uuid, l| {
    let cron_schedule = Cron_Schedule::from_str(&cron_expression).unwrap();
    let next_run_time_vec: Vec<DateTime<Utc>> = cron_schedule.upcoming(Utc).take(1)
                  .filter_map(|datetime| Some(datetime)).collect::<Vec<DateTime<Utc>>>();
    println!("cron job next run time: {}", next_run_time_vec[0].to_string());
 }).await.unwrap());
```

**Comment by mvniekerk** [comment]
Hi @Hellager 
Thanks for the post - I'll check into this

**Comment by mvniekerk** [comment]
So @Hellager 
Have a look
https://github.com/mvniekerk/tokio-cron-scheduler/releases/tag/v0.8.1

Implemented.
