### ISSUE TITLE
can I use await in the job?

### ISSUE THREAD

**Issue by mrxiaozhuox** [mvniekerk/tokio-cron-scheduler#4]
How do I use the await statement in a closure function?

```rust
        self.job_scheduler.add(Job::new(schedule,|uuid, l| {
            DB_MANAGER.lock().await;
        }).unwrap());
```
this is my code.

**Comment by mvniekerk** [comment]
@mrxiaozhuox Async closures can't be done (yet). I'll check if there's maybe another around it

**Comment by hgaiser** [comment]
Why was this closed? I'm wondering the same thing, there doesn't seem to be a solution yet?

**Comment by mvniekerk** [comment]
Cucumber-rs has a way to add async closures - sort of.
Plan is to glean off from it

**Comment by mvniekerk** [comment]
v0.3.1 has them now.
