### ISSUE TITLE
hi, can you support some shortcut to create cron expresions, such as daily? 

### ISSUE THREAD

**Issue by vidyli** [mvniekerk/tokio-cron-scheduler#6]
please check [cron_clock](https://crates.io/crates/cron_clock)

**Comment by mvniekerk** [comment]
Thanks @vidyli  for the bug report.
The cron crate (https://github.com/zslayton/cron)  I'm using for parsing the cron statements supports '@hourly',  '@daily',  '@weekly',  '@monthly' and  '@yearly'.
As I'm using the upstream parser, I'll rather defer you to them if you've got another use case.

**Comment by mvniekerk** [comment]
I've updated the README to reflect this
